
version: '3.9'

services:
  web:
    build: ./todo_service
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://todo_service:todo_service_password@db:5432/todo_service
      - NOTIFICATION_URL=http://notification:8009
    depends_on:
      - db
      - notification
  notification:
    build: ./notification_service
    command: uvicorn main:app --host 0.0.0.0 --port 8009
    volumes:
      - .:/app
    expose:
      - 8009
    ports:
      - 8009:8009
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432    
    environment:
      - POSTGRES_USER=todo_service
      - POSTGRES_PASSWORD=todo_service_password
      - POSTGRES_DB=todo_service

volumes:
  postgres_data: